"""Add tipo and unique constraint to Apoyo model

Revision ID: 411bc66fffcf
Revises: 
Create Date: 2025-10-27 18:35:33.163635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '411bc66fffcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - ADJUSTED ###

    # --- KEEP: Changes for the Apoyo table ---
    with op.batch_alter_table('apoyos', schema=None) as batch_op:
        # NOTE: If 'apoyos.id' already exists, comment out the line below.
        # batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

        # Add the 'tipo' column with a server default
        batch_op.add_column(sa.Column('tipo', sa.String(length=10), nullable=False, server_default='like'))

        # Add the unique constraint
        batch_op.create_unique_constraint('uq_usuario_reporte', ['usuario_id', 'reporte_id'])

    # --- REMOVE/COMMENT OUT: All other auto-detected changes ---
    """ 
    # These were likely due to mismatches or Alembic confusion. Keep commented out.
    op.create_table('estados_reporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_estado')
    )
    op.create_table('historial_estados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_cambio', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reporte_id', sa.Integer(), nullable=False),
    sa.Column('estado_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estado_id'], ['estados_reporte.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True) # <-- This block caused the error

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('entidades_publicas', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_constraint('funcionarios_legajo_key', type_='unique') # Assuming f() didn't work

    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.create_unique_constraint(None, ['imagen'])

    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    """
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - needs adjustment if upgrade was modified ###
    # NOTE: This downgrade might need manual adjustment if you commented out parts of upgrade()
    #       or if the original auto-generated downgrade was incorrect.
    
    # --- Reverting Apoyo changes ---
    with op.batch_alter_table('apoyos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_usuario_reporte', type_='unique')
        batch_op.drop_column('tipo')
        # If you commented out adding the 'id' in upgrade(), comment this out too.
        # batch_op.drop_column('id') 

    # --- Reverting other changes (Keep commented out as in upgrade) ---
    """
    with op.batch_alter_table('zonas', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('reportes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        # Check if this constraint name is correct or needs f() wrapper
        batch_op.create_unique_constraint('funcionarios_legajo_key', ['legajo']) 
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('entidades_publicas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('comentarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('historial_estados')
    op.drop_table('estados_reporte')
    """
    # ### end Alembic commands ###