name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /home/ubuntu/backend_urbanfix
            echo ">>> Fetching latest changes..."
            git fetch origin main
            git reset --hard origin/main
            echo ">>> Pull complete."

            # Activar el entorno virtual y reinstalar dependencias (por si cambió algo)
            source venv/bin/activate
            pip install -r requirements.txt --upgrade

            # Reiniciar el servicio systemd
            echo ">>> Restarting Gunicorn service..."
            sudo systemctl daemon-reload
            sudo systemctl restart urbanfix.service

            echo ">>> Deployment complete "
